[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "22.2.2"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "11.2.7"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Azure/azure-event-hubs-go"
  version = "1.0.1"

[[constraint]]
  name = "github.com/denisenkom/go-mssqldb"
  branch = "master"

[[constraint]]
  name = "github.com/globalsign/mgo"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.0"
