[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  branch = "master"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "^10.12.0"

[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "1.1.0"
